export const GET_RECIPES = "GET_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const POST_RECIPE = "POST_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const SET_ERROR = "SET_ERROR";

export const NAVIGATE_TO_HOME_PAGE = "NAVIGATE_TO_HOME_PAGE";
export const NAVIGATE_TO_RECIPE_PAGE = "NAVIGATE_TO_RECIPE_PAGE";
export const NAVIGATE_TO_RECIPE_FORM = "NAVIGATE_TO_RECIPE_FORM";
export const NAVIGATE_TO_PROFILE_PAGE = "NAVIGATE_TO_PROFILE_PAGE";

export const LOG_IN = "LOG_IN";
export const LOG_OFF = "LOG_OFF";
export const LOG_IN_SAVED_USER = "LOG_IN_SAVED_USER";
export const SET_LOG_IN_STATUS = "SET_LOG_IN_STATUS";
export const LOAD_USER = "LOAD_USER";
export const SET_USER_INFORMATION = "SET_USER_INFORMATION";
